"""initial schema

Revision ID: 22ca49ca2ede
Revises: 
Create Date: 2026-08-05 07:27:46.526512
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '22ca49ca2ede'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # `CREATE SCHEMA` is not something SQLAlchemy's autogenerate emits, even
    # with include_schemas=True (that flag only affects introspection of
    # existing objects) -- added by hand, ahead of every table below that
    # lives in the `pdm` schema.
    op.execute("CREATE SCHEMA IF NOT EXISTS pdm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_record',
    sa.Column('calibration_record_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('equipment_family', sa.String(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('reference_class', sa.String(), nullable=False),
    sa.Column('taxonomy_version', sa.String(), nullable=False),
    sa.Column('stratum', sa.String(), nullable=False),
    sa.Column('compartments', postgresql.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('calibration_population', sa.Integer(), nullable=False),
    sa.Column('effective_sample_size', sa.Numeric(), nullable=False),
    sa.Column('events_observed', sa.Numeric(), nullable=False),
    sa.Column('powered', sa.Boolean(), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('fit_artifact_uri', sa.String(), nullable=True),
    sa.Column('reliability_curve', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weighted_calibration_error', sa.Numeric(), nullable=False),
    sa.Column('unweighted_calibration_error', sa.Numeric(), nullable=False),
    sa.Column('picp_rul', sa.Numeric(), nullable=True),
    sa.Column('drift_state', sa.String(), nullable=False),
    sa.Column('drift_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("drift_state IN ('stable','warning','drifting','withdrawn')", name='calibration_drift_state'),
    sa.CheckConstraint("method IN ('isotonic','beta','identity_suppressed')", name='calibration_method'),
    sa.CheckConstraint("stratum IN ('treated','policy_frozen')", name='calibration_stratum'),
    sa.CheckConstraint('tier BETWEEN 0 AND 3', name='calibration_tier_range'),
    sa.PrimaryKeyConstraint('calibration_record_id'),
    sa.UniqueConstraint('tier', 'equipment_family', 'horizon_days', 'reference_class', 'taxonomy_version', 'stratum', 'compartments', 'window_end'),
    schema='pdm'
    )
    op.create_table('prediction_provenance',
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('scoring_run_id', sa.UUID(), nullable=False),
    sa.Column('model_binding_id', sa.UUID(), nullable=False),
    sa.Column('label_set_id', sa.UUID(), nullable=False),
    sa.Column('propensity_model_id', sa.UUID(), nullable=True),
    sa.Column('calibration_record_id', sa.UUID(), nullable=True),
    sa.Column('gate_decision', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_observations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_definition_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fallback_path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attribution_method', sa.String(), nullable=True),
    sa.Column('stability_threshold_applied', sa.Numeric(), nullable=True),
    sa.Column('suppressed_factor_count', sa.Integer(), nullable=False),
    sa.Column('suppressed_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('transition_annotation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('read_model_lag', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('per_asset_label_lag_days', sa.Numeric(), nullable=True),
    sa.Column('classification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('provenance_id'),
    schema='pdm'
    )
    op.create_table('scoring_run',
    sa.Column('scoring_run_id', sa.UUID(), nullable=False),
    sa.Column('stratum', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('baseline_epoch_at_start', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('baseline_epoch_at_publish', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model_bindings', postgresql.ARRAY(sa.UUID()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('label_set_ids', postgresql.ARRAY(sa.UUID()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('feature_definition_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('domino_execution_ref', sa.String(), nullable=False),
    sa.Column('predictions_written', sa.Integer(), nullable=True),
    sa.Column('predictions_rejected', sa.Integer(), nullable=True),
    sa.Column('rejection_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('read_model_lag_at_start', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','ingesting','published','fenced_out','failed')", name='scoring_run_status'),
    sa.CheckConstraint("stratum IN ('operational','holdout_research')", name='scoring_run_stratum'),
    sa.CheckConstraint("trigger IN ('scheduled','mission_completed','on_demand','tier_migration','invalidation_rescore','binding_activation','design_change_projection')", name='scoring_run_trigger'),
    sa.PrimaryKeyConstraint('scoring_run_id'),
    schema='pdm'
    )
    op.create_table('tier_policy',
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('band_thresholds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hysteresis', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sme_validated', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('policy_version'),
    schema='pdm'
    )
    op.create_table('criticality_assessment',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('niin', sa.String(length=9), nullable=False),
    sa.Column('equipment_family', sa.String(), nullable=False),
    sa.Column('taxonomy_version', sa.String(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('input_mission_criticality', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('input_consequence_of_failure', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('input_casrep_history', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('input_sensor_availability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('input_fleet_population', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('input_provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('proposed_tier', sa.SmallInteger(), nullable=False),
    sa.Column('data_availability_ceiling', sa.SmallInteger(), nullable=False),
    sa.Column('assigned_tier', sa.SmallInteger(), nullable=False),
    sa.Column('tier_policy_version', sa.String(), nullable=False),
    sa.Column('previous_tier', sa.SmallInteger(), nullable=True),
    sa.Column('transition_id', sa.UUID(), nullable=True),
    sa.Column('transition_reason', sa.String(), nullable=True),
    sa.Column('rescore_scoring_run_id', sa.UUID(), nullable=True),
    sa.Column('attributable_level_shift', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('assigned_tier = LEAST(proposed_tier, data_availability_ceiling)', name='tier_is_capped'),
    sa.CheckConstraint('assigned_tier BETWEEN 0 AND 3', name='criticality_assigned_tier_range'),
    sa.CheckConstraint('data_availability_ceiling BETWEEN 0 AND 3', name='criticality_ceiling_range'),
    sa.CheckConstraint('previous_tier IS NULL OR previous_tier BETWEEN 0 AND 3', name='criticality_previous_tier_range'),
    sa.CheckConstraint('proposed_tier BETWEEN 0 AND 3', name='criticality_proposed_tier_range'),
    sa.CheckConstraint('published_at IS NULL OR previous_tier IS NULL OR rescore_scoring_run_id IS NOT NULL', name='migration_requires_rescore'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='criticality_score_range'),
    sa.ForeignKeyConstraint(['rescore_scoring_run_id'], ['pdm.scoring_run.scoring_run_id'], ),
    sa.ForeignKeyConstraint(['tier_policy_version'], ['pdm.tier_policy.policy_version'], ),
    sa.PrimaryKeyConstraint('assessment_id'),
    schema='pdm'
    )
    op.create_table('prediction',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('scoring_run_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('installed_item_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('niin', sa.String(length=9), nullable=False),
    sa.Column('equipment_family', sa.String(), nullable=False),
    sa.Column('baseline_id', sa.UUID(), nullable=False),
    sa.Column('baseline_epoch', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('p_failure', sa.Numeric(), nullable=True),
    sa.Column('reference_class', sa.String(), nullable=False),
    sa.Column('sharpness', sa.Numeric(), nullable=False),
    sa.Column('calibration_population', sa.Integer(), nullable=False),
    sa.Column('rul', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('population_hazard_rate', sa.Numeric(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('fallback_level', sa.SmallInteger(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('contributing_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('serving_class', sa.String(), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidation_cause', sa.String(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('provenance_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("(calibration_population >= 50) OR (reference_class = 'class_estimate' AND p_failure IS NULL AND population_hazard_rate IS NOT NULL)", name='calibration_gate'),
    sa.CheckConstraint("(reference_class = 'item' AND rul IS NOT NULL AND population_hazard_rate IS NULL) OR (reference_class <> 'item' AND rul IS NULL AND population_hazard_rate IS NOT NULL)", name='rul_only_when_item_conditional'),
    sa.CheckConstraint('calibration_population >= 50 OR fallback_level >= 3', name='sub_gate_is_deep_fallback'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='prediction_confidence_range'),
    sa.CheckConstraint('fallback_level BETWEEN 0 AND 4', name='prediction_fallback_level_range'),
    sa.CheckConstraint('horizon_days > 0', name='prediction_horizon_positive'),
    sa.CheckConstraint('p_failure IS NULL OR (p_failure >= 0 AND p_failure <= 1)', name='prediction_p_failure_range'),
    sa.CheckConstraint('p_failure IS NULL OR calibration_population >= 50', name='p_failure_requires_a_calibrated_cell'),
    sa.CheckConstraint('population_hazard_rate IS NULL OR population_hazard_rate >= 0', name='prediction_hazard_rate_nonneg'),
    sa.CheckConstraint('tier BETWEEN 0 AND 3', name='prediction_tier_range'),
    sa.ForeignKeyConstraint(['provenance_id'], ['pdm.prediction_provenance.provenance_id'], ),
    sa.ForeignKeyConstraint(['scoring_run_id'], ['pdm.scoring_run.scoring_run_id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['pdm.prediction.prediction_id'], ),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('installed_item_id', 'horizon_days', 'scoring_run_id'),
    schema='pdm'
    )
    op.create_table('inbox',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('producer_slug', sa.String(), nullable=False),
    sa.Column('producer_node_id', sa.String(), nullable=False),
    sa.Column('monotonic_seq', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('aggregate', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('kafka_partition', sa.Integer(), nullable=True),
    sa.Column('kafka_offset', sa.BigInteger(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingest_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_quality', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_on_epoch', sa.BigInteger(), nullable=True),
    sa.Column('blocked_since_mono', sa.BigInteger(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('replay', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('producer_slug', 'producer_node_id', 'monotonic_seq', name='inbox_seq_unique')
    )
    op.create_index('inbox_blocked', 'inbox', ['blocked_on_epoch'], unique=False, postgresql_where='blocked_on_epoch IS NOT NULL')
    op.create_index('inbox_unprocessed', 'inbox', ['received_at'], unique=False, postgresql_where='processed_at IS NULL')
    op.create_table('outbox',
    sa.Column('outbox_id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('producer_slug', sa.String(), nullable=False),
    sa.Column('producer_version', sa.String(), nullable=False),
    sa.Column('producer_node_id', sa.String(), nullable=False),
    sa.Column('monotonic_seq', sa.BigInteger(), nullable=False),
    sa.Column('hlc_physical_ms', sa.BigInteger(), nullable=False),
    sa.Column('hlc_logical', sa.Integer(), nullable=False),
    sa.Column('hlc_node_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('partition_key', sa.String(), nullable=False),
    sa.Column('compaction_key', sa.String(), nullable=True),
    sa.Column('aggregate', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('subject', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('baseline_epoch', sa.BigInteger(), nullable=True),
    sa.Column('classification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('causation_id', sa.String(length=36), nullable=True),
    sa.Column('replay', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingest_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_quality', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('payload_ref', sa.String(), nullable=True),
    sa.Column('payload_sha256', sa.LargeBinary(), nullable=False),
    sa.Column('payload_kek_id', sa.String(), nullable=False),
    sa.Column('record_signature', sa.LargeBinary(), nullable=False),
    sa.Column('signing_key_id', sa.String(), nullable=False),
    sa.Column('shard', sa.SmallInteger(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_until_mono', sa.BigInteger(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_by_shore_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('compaction_key IS NULL OR compaction_key <> partition_key', name='outbox_compaction_key_distinct'),
    sa.CheckConstraint('payload_ciphertext IS NOT NULL OR payload_ref IS NOT NULL', name='outbox_payload_present'),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('producer_slug', 'producer_node_id', 'monotonic_seq', name='outbox_seq_unique')
    )
    op.create_index('outbox_prunable', 'outbox', ['published_at'], unique=False, postgresql_where='published_at IS NOT NULL')
    op.create_index('outbox_unpublished', 'outbox', ['shard', 'outbox_id'], unique=False, postgresql_where='published_at IS NULL')
    op.create_table('producer_sequence',
    sa.Column('producer_slug', sa.String(), nullable=False),
    sa.Column('producer_node_id', sa.String(), nullable=False),
    sa.Column('next_seq', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('producer_slug', 'producer_node_id')
    )
    op.create_table('remediated_selectors',
    sa.Column('selector_hash', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('remediation_id', sa.String(length=36), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('selector_hash')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', 'route_id', 'principal_id')
    )
    # ### end Alembic commands ###

    # --- 22-pdm.md §4.5 / §11.3.1: holdout isolation via RLS ---------------
    # Not expressible via SQLAlchemy's ORM/autogenerate -- transcribed here
    # by hand, verbatim against the spec. Three policies split by command,
    # two roles: serving (actionable + research_only visible on read,
    # writable only as actionable/research_only) and research (SELECT-only,
    # research_only rows only).
    op.execute("CREATE ROLE fathom_pdm_serving")
    # Without schema USAGE, the table-level GRANT below is inert: Postgres
    # checks schema USAGE before object privileges, so every query this role
    # issues would fail with "permission denied for schema pdm" -- caught
    # only by actually querying as this role, not by reading the DDL.
    op.execute("GRANT USAGE ON SCHEMA pdm TO fathom_pdm_serving")
    # No UPDATE grant here -- see the invalidate_prediction() function below
    # for why a direct UPDATE grant on this role cannot do what invalidation
    # needs, regardless of what its policy's USING clause says.
    op.execute("GRANT SELECT, INSERT ON pdm.prediction TO fathom_pdm_serving")

    op.execute(
        "CREATE POLICY actionable_read ON pdm.prediction "
        "FOR SELECT TO fathom_pdm_serving "
        "USING (serving_class = 'actionable')"
    )
    op.execute(
        "CREATE POLICY serving_insert ON pdm.prediction "
        "FOR INSERT TO fathom_pdm_serving "
        "WITH CHECK (serving_class IN ('actionable', 'research_only'))"
    )

    # Research path: a distinct role, distinct connection pool, SELECT only.
    # Holds no INSERT/UPDATE/DELETE anywhere -- the truth partition's
    # credential separation (13 §8.6).
    op.execute("CREATE ROLE fathom_pdm_research")
    op.execute("GRANT USAGE ON SCHEMA pdm TO fathom_pdm_research")
    op.execute("GRANT SELECT ON pdm.prediction TO fathom_pdm_research")
    op.execute(
        "CREATE POLICY research_only ON pdm.prediction "
        "FOR SELECT TO fathom_pdm_research "
        "USING (serving_class = 'research_only')"
    )

    op.execute("ALTER TABLE pdm.prediction ENABLE ROW LEVEL SECURITY")
    # FORCE closes the table-owner bypass -- without it, the role that ran
    # this migration (which owns the table) would see every row regardless
    # of policy.
    op.execute("ALTER TABLE pdm.prediction FORCE ROW LEVEL SECURITY")

    # --- Invalidation: a SECURITY DEFINER function, not a policy ----------
    # [CORRECTION, verified against a real container] 22-pdm.md's original
    # `serving_invalidate` policy (`FOR UPDATE ... USING (true)`) was meant
    # to let fathom_pdm_serving invalidate a research_only row it can never
    # SELECT. That doesn't work: PostgreSQL requires UPDATE's target row to
    # also satisfy any applicable SELECT policy for the same role (UPDATE's
    # WHERE clause is itself a read), so `actionable_read`'s
    # `serving_class = 'actionable'` USING clause silently vetoed every
    # UPDATE against a research_only row regardless of `serving_invalidate`'s
    # own USING(true) -- confirmed empirically: the split-policy form always
    # updated zero rows for a holdout prediction. No combination of
    # SELECT/UPDATE policies on the same role can express "writable but not
    # readable," because Postgres's RLS model has no such distinction.
    #
    # The actual mechanism: a narrowly-scoped SECURITY DEFINER function,
    # owned by a dedicated BYPASSRLS role that fathom_pdm_serving cannot
    # otherwise assume, EXECUTE-granted to fathom_pdm_serving alone. The
    # function's body is the entire narrow write it performs -- it cannot be
    # used to read, join, or supersede a row's serving_class.
    op.execute("CREATE ROLE fathom_pdm_invalidator BYPASSRLS")
    op.execute("GRANT USAGE ON SCHEMA pdm TO fathom_pdm_invalidator")
    op.execute("GRANT SELECT, UPDATE ON pdm.prediction TO fathom_pdm_invalidator")
    op.execute(
        """
        CREATE FUNCTION pdm.invalidate_prediction(p_prediction_id uuid, p_cause text)
        RETURNS boolean
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pdm, pg_temp
        AS $fn$
        DECLARE
            v_row_count int;
        BEGIN
            UPDATE pdm.prediction
            SET status = 'invalidated',
                invalidation_cause = p_cause,
                invalidated_at = now()
            WHERE prediction_id = p_prediction_id
              AND serving_class IN ('actionable', 'research_only');
            GET DIAGNOSTICS v_row_count = ROW_COUNT;
            RETURN v_row_count > 0;
        END;
        $fn$
        """
    )
    op.execute("ALTER FUNCTION pdm.invalidate_prediction(uuid, text) OWNER TO fathom_pdm_invalidator")
    op.execute("REVOKE ALL ON FUNCTION pdm.invalidate_prediction(uuid, text) FROM PUBLIC")
    op.execute("GRANT EXECUTE ON FUNCTION pdm.invalidate_prediction(uuid, text) TO fathom_pdm_serving")


def downgrade() -> None:
    op.execute("REVOKE EXECUTE ON FUNCTION pdm.invalidate_prediction(uuid, text) FROM fathom_pdm_serving")
    op.execute("DROP FUNCTION IF EXISTS pdm.invalidate_prediction(uuid, text)")
    op.execute("REVOKE ALL ON pdm.prediction FROM fathom_pdm_invalidator")
    op.execute("REVOKE USAGE ON SCHEMA pdm FROM fathom_pdm_invalidator")
    op.execute("DROP ROLE IF EXISTS fathom_pdm_invalidator")

    op.execute("ALTER TABLE pdm.prediction NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE pdm.prediction DISABLE ROW LEVEL SECURITY")
    op.execute("DROP POLICY IF EXISTS research_only ON pdm.prediction")
    op.execute("DROP POLICY IF EXISTS serving_insert ON pdm.prediction")
    op.execute("DROP POLICY IF EXISTS actionable_read ON pdm.prediction")
    op.execute("REVOKE ALL ON pdm.prediction FROM fathom_pdm_research")
    op.execute("REVOKE USAGE ON SCHEMA pdm FROM fathom_pdm_research")
    op.execute("DROP ROLE IF EXISTS fathom_pdm_research")
    op.execute("REVOKE ALL ON pdm.prediction FROM fathom_pdm_serving")
    op.execute("REVOKE USAGE ON SCHEMA pdm FROM fathom_pdm_serving")
    op.execute("DROP ROLE IF EXISTS fathom_pdm_serving")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_keys')
    op.drop_table('remediated_selectors')
    op.drop_table('producer_sequence')
    op.drop_index('outbox_unpublished', table_name='outbox', postgresql_where='published_at IS NULL')
    op.drop_index('outbox_prunable', table_name='outbox', postgresql_where='published_at IS NOT NULL')
    op.drop_table('outbox')
    op.drop_index('inbox_unprocessed', table_name='inbox', postgresql_where='processed_at IS NULL')
    op.drop_index('inbox_blocked', table_name='inbox', postgresql_where='blocked_on_epoch IS NOT NULL')
    op.drop_table('inbox')
    op.drop_table('prediction', schema='pdm')
    op.drop_table('criticality_assessment', schema='pdm')
    op.drop_table('tier_policy', schema='pdm')
    op.drop_table('scoring_run', schema='pdm')
    op.drop_table('prediction_provenance', schema='pdm')
    op.drop_table('calibration_record', schema='pdm')
    # ### end Alembic commands ###

    # Mirrors the hand-added CREATE SCHEMA in upgrade().
    op.execute("DROP SCHEMA IF EXISTS pdm")
