/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/gateway/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Login */
        get: operations["gateway_session_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/session/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Callback */
        get: operations["gateway_session_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Identity */
        get: operations["gateway_get_session_identity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Logout */
        post: operations["gateway_session_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdm/scoring-runs/{scoring_run_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Ingest */
        post: operations["pdm_bulk_ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdm/predictions/{prediction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction */
        get: operations["pdm_get_prediction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdm/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Predictions */
        get: operations["pdm_list_predictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdm/scoring-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Scoring Run */
        post: operations["pdm_create_scoring_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdm/criticality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Criticality */
        get: operations["pdm_get_criticality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdm/expected-consequence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Expected Consequence */
        post: operations["pdm_compute_expected_consequence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdm/model-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Model Binding */
        post: operations["pdm_create_model_binding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdm/model-bindings/{binding_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Model Binding */
        post: operations["pdm_activate_model_binding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Basis
         * @enum {string}
         */
        Basis: "item_conditional" | "class_rate_converted";
        /**
         * BulkPredictionIngestRequest
         * @description 22-pdm.md §2.5: 'The bulk ingest schema does NOT contain
         *     `serving_class` -- a caller cannot set it, cannot override it.'
         */
        BulkPredictionIngestRequest: {
            /** Predictions */
            predictions: components["schemas"]["FailurePrediction"][];
        };
        /** BulkPredictionIngestResult */
        BulkPredictionIngestResult: {
            /**
             * Scoring Run Id
             * Format: uuid
             */
            scoring_run_id: string;
            /** Predictions Written */
            predictions_written: number;
            /** Predictions Rejected */
            predictions_rejected: number;
            /**
             * Rejection Summary
             * @default []
             */
            rejection_summary: string[];
        };
        /**
         * ContributingFactor
         * @description Renamed from `drivers` [D23]. A causal statement must cite an
         *     adjudicated Failure Intelligence hypothesis -- this is never one.
         */
        ContributingFactor: {
            /** Factor */
            factor: string;
            /** Contribution */
            contribution: number;
            /** Attribution Method */
            attribution_method: string;
            /**
             * Stability
             * @description Rank stability across runs or bootstrap.
             */
            stability: number;
            /**
             * Observation Ref
             * @description Points at a feature observation, NOT at itself.
             */
            observation_ref: string;
        };
        /** CreateModelBindingRequest */
        CreateModelBindingRequest: {
            /** Tier */
            tier: number;
            /** Equipment Family */
            equipment_family: string;
            /** Taxonomy Version */
            taxonomy_version: string;
            /** Registry Model Version */
            registry_model_version: string;
            /** Registry Model Uri */
            registry_model_uri: string;
            /** Approval Ref */
            approval_ref: string;
            /**
             * Label Set Id
             * Format: uuid
             */
            label_set_id: string;
        };
        /** CreateScoringRunRequest */
        CreateScoringRunRequest: {
            /**
             * Stratum
             * @enum {string}
             */
            stratum: "operational" | "holdout_research";
            /** Scope */
            scope: {
                [key: string]: unknown;
            };
        };
        /** ExpectedConsequence */
        ExpectedConsequence: {
            /**
             * P Event Horizon
             * @description Probability of the event within the horizon, on a COMMON basis.
             */
            p_event_horizon: number;
            /**
             * P Event Lower
             * @description Epistemic interval, widened by fallback_level and cell size.
             */
            p_event_lower: number;
            /** P Event Upper */
            p_event_upper: number;
            basis: components["schemas"]["Basis"];
            /** Consequence Value */
            consequence_value: number;
            /**
             * Expected Consequence
             * @description THE only rankable quantity.
             */
            expected_consequence: number;
            timing_basis: components["schemas"]["TimingBasis"];
            /**
             * Timing P10
             * @description None unless timing_basis is rul_quantiles.
             */
            timing_p10?: number | null;
            /** Timing P50 */
            timing_p50?: number | null;
            /** Conversion Version */
            conversion_version: string;
            /** Inputs Digest */
            inputs_digest: string;
        };
        /** FailurePrediction */
        FailurePrediction: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /**
             * Installed Item Id
             * Format: uuid
             */
            installed_item_id: string;
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /** Niin */
            niin: string;
            /** Equipment Family */
            equipment_family: string;
            /**
             * Baseline Id
             * Format: uuid
             */
            baseline_id: string;
            /** Baseline Epoch */
            baseline_epoch: number;
            /** Horizon Days */
            horizon_days: number;
            /**
             * P Failure
             * @description NULL when calibration_population < 50. A predicted probability that cannot be calibrated must not be emitted merely because the field exists; omission is the honest signal.
             */
            p_failure?: number | null;
            reference_class: components["schemas"]["ReferenceClass"];
            /**
             * Sharpness
             * @description Dispersion relative to the reference-class base rate.
             */
            sharpness: number;
            /** Calibration Population */
            calibration_population?: number | null;
            /** @description Omitted where not item-conditional. */
            rul?: components["schemas"]["Rul"] | null;
            /**
             * Population Hazard Rate
             * @description Emitted INSTEAD OF `rul` for non-item reference classes.
             */
            population_hazard_rate?: number | null;
            /**
             * Confidence
             * @description Sharpness-and-fit confidence only.
             */
            confidence: number;
            /**
             * Fallback Level
             * @description Cold-start depth, NOT folded into confidence.
             */
            fallback_level: number;
            /**
             * Tier
             * @description Transparency only. Never branch on this -- FTH006.
             */
            tier: number;
            /**
             * Contributing Factors
             * @default []
             */
            contributing_factors: components["schemas"]["ContributingFactor"][];
            /** Model Version */
            model_version: string;
            /**
             * Scoring Run Id
             * Format: uuid
             */
            scoring_run_id: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /** ModelBindingResponse */
        ModelBindingResponse: {
            /**
             * Binding Id
             * Format: uuid
             */
            binding_id: string;
            /** Tier */
            tier: number;
            /** Equipment Family */
            equipment_family: string;
            /** Taxonomy Version */
            taxonomy_version: string;
            /** Registry Model Version */
            registry_model_version: string;
            /** Registry Model Uri */
            registry_model_uri: string;
            /** Approval Ref */
            approval_ref: string;
            /**
             * Label Set Id
             * Format: uuid
             */
            label_set_id: string;
            /** Censoring Correction */
            censoring_correction: string;
            /** Activated At */
            activated_at: string | null;
            /** Deactivated At */
            deactivated_at: string | null;
        };
        /**
         * ReferenceClass
         * @enum {string}
         */
        ReferenceClass: "item" | "niin_fleet" | "equipment_family" | "class_estimate";
        /**
         * RiskPosture
         * @description [PLACEHOLDER P-17] Program decision, not an analytic one -- 22-pdm.md
         *     §7.4: "it encodes how much the Navy is willing to spend to avoid an
         *     unlikely severe failure." Default AVERSE for the highest consequence
         *     band, NEUTRAL otherwise.
         * @enum {string}
         */
        RiskPosture: "NEUTRAL" | "AVERSE";
        /** Rul */
        Rul: {
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
            unit: components["schemas"]["RulUnit"];
        };
        /**
         * RulUnit
         * @enum {string}
         */
        RulUnit: "days" | "steaming_hours" | "eoh" | "cycles" | "sorties" | "dives";
        /** ScoringRunResponse */
        ScoringRunResponse: {
            /**
             * Scoring Run Id
             * Format: uuid
             */
            scoring_run_id: string;
            /** Stratum */
            stratum: string;
            /** Trigger */
            trigger: string;
            /** Scope */
            scope: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Feature Definition Time */
            feature_definition_time: string;
        };
        /**
         * TimingBasis
         * @enum {string}
         */
        TimingBasis: "rul_quantiles" | "mean_residual_life_from_rate" | "none";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    gateway_session_login: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gateway_session_callback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                fathom_login?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gateway_get_session_identity: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                fathom_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gateway_session_logout: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "X-Fathom-CSRF"?: string | null;
            };
            path?: never;
            cookie?: {
                fathom_session?: string | null;
                fathom_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdm_bulk_ingest: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                scoring_run_id: string;
            };
            cookie?: {
                fathom_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdm_get_prediction: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                prediction_id: string;
            };
            cookie?: {
                fathom_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdm_list_predictions: {
        parameters: {
            query?: {
                asset_id?: string | null;
                installed_item_id?: string | null;
                niin?: string | null;
                equipment_family?: string | null;
                reference_class?: string | null;
                limit?: number;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                fathom_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdm_create_scoring_run: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                fathom_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdm_get_criticality: {
        parameters: {
            query: {
                niin: string;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                fathom_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdm_compute_expected_consequence: {
        parameters: {
            query: {
                consequence_value: number;
                consequence_band: string;
                risk_posture?: components["schemas"]["RiskPosture"];
                operating_fraction?: number;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                fathom_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdm_create_model_binding: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                fathom_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdm_activate_model_binding: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                binding_id: string;
            };
            cookie?: {
                fathom_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
